kind: pipeline
type: docker
name: publish

steps:
  - name: Greet
    image: alpine
    commands:
      - echo hello world

  - name: Build
    image: ubuntu:latest
    commands:
      - apt-get update
      - apt-get install hugo
      - hugo
      - ls public
