kind: pipeline
type: docker
name: publish

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main

steps:
  - name: submodules
    image: alpine/git
    commands:
      - git submodule update --init --recursive

  - name: build
    image: alpine
    commands:
      - apk add hugo
      - hugo

  - name: publish
    image: instrumentisto/rsync-ssh
    commands:
      - echo "$PRIVATE_KEY" >> id_rsa
      - chmod 600 id_rsa
      - cd public
      - rsync -avz -e 'ssh -i ../id_rsa -o StrictHostKeyChecking=no' --progress ./* root@aricodes.net:/opt/aricodes/
    environment:
      PRIVATE_KEY:
        from_secret: PRIVATE_KEY
