baseURL = "/"
languageCode = "en-us"
title = "Ari Codes"
theme = "terminal"

[params]
contentTypeName = "posts"
themeColor = "blue"
fullWidthTheme = false
centerTheme = true

[params.twitter]
creator = "realwillowtw"
site = "aricodes.net"

[languages]

[languages.en]
name = "English"

[languages.en.params.logo]
logoText = "Ari Codes"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"

[[languages.en.menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"

[[languages.en.menu.main]]
identifier = "patreon"
name = "Patreon"
url = "https://www.patreon.com/aricodes"
