baseURL = "/"
languageCode = "en-us"
title = "Ari Codes"
theme = "terminal"

[params]
contentTypeName = "posts"
fullWidthTheme = false
centerTheme = true

[params.page.code]
copy = true
maxShownLines = -1

[languages]

[languages.en.params]
name = "English"
owner = "Aria Taylor"
readMore = "Read More"

[languages.en.params.logo]
logoText = "Ari Codes"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About"
url = "/about"

[[languages.en.menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact"

[[languages.en.menu.main]]
identifier = "kofi"
name = "Buy Me a Coffee"
url = "https://ko-fi.com/aricodes"
