name: Publish site

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and publish
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.86.0'
          extended: true

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Generate known_hosts
        run: ssh-keyscan -H aricodes.net >> ~/.ssh/known_hosts

      - name: Build
        run: hugo

      - name: Deploy
        run: rsync -vz ./* gh-actions@aricodes.net:/opt/aricodes/
        working-directory: ./public
